// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `read_f32_register`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `cmp`, `cmp`, `eq`, `eq`, `fmt`, `fmt`, `hash`, `hash`, `partial_cmp`, `partial_cmp`

/// Reads the USB register and returns structured status
Future<UsbStatus> readUsbStatus() =>
    NativeConfig.instance.api.crateApiReadUsbStatus();

/// Reads the PCIe register and returns structured status
Future<PcieStatus> readPcieStatus() =>
    NativeConfig.instance.api.crateApiReadPcieStatus();

/// Reads the interrupt/alert register and returns structured status
Future<IntrAlertStatus> readIntrAlertStatus() =>
    NativeConfig.instance.api.crateApiReadIntrAlertStatus();

/// Reads the power/clock register and returns structured status
Future<PwrClkStatus> readPwrClkStatus() =>
    NativeConfig.instance.api.crateApiReadPwrClkStatus();

/// Reads the interface mux register and returns structured status
Future<InterfaceMuxStatus> readInterfaceMuxStatus() =>
    NativeConfig.instance.api.crateApiReadInterfaceMuxStatus();

Future<void> connectToBoard({required String targetMac}) =>
    NativeConfig.instance.api.crateApiConnectToBoard(targetMac: targetMac);

Future<void> setSimulationMode({required bool on_}) =>
    NativeConfig.instance.api.crateApiSetSimulationMode(on_: on_);

Future<bool> togglePower() => NativeConfig.instance.api.crateApiTogglePower();

Future<void> toggleUsb0Power({required bool enable}) =>
    NativeConfig.instance.api.crateApiToggleUsb0Power(enable: enable);

Future<void> toggleUsb0Reset({required bool enable}) =>
    NativeConfig.instance.api.crateApiToggleUsb0Reset(enable: enable);

Future<void> toggleUsb1Power({required bool enable}) =>
    NativeConfig.instance.api.crateApiToggleUsb1Power(enable: enable);

Future<void> toggleUsb1Reset({required bool enable}) =>
    NativeConfig.instance.api.crateApiToggleUsb1Reset(enable: enable);

Future<void> setSataPower({required int level}) =>
    NativeConfig.instance.api.crateApiSetSataPower(level: level);

Future<void> setPcieOutputs({required int level}) =>
    NativeConfig.instance.api.crateApiSetPcieOutputs(level: level);

Future<void> toggleSerdesClock({required bool enable}) =>
    NativeConfig.instance.api.crateApiToggleSerdesClock(enable: enable);

Future<void> toggleI2CMuxReset({required bool enable}) =>
    NativeConfig.instance.api.crateApiToggleI2CMuxReset(enable: enable);

Future<void> toggleFtdiReset({required bool enable}) =>
    NativeConfig.instance.api.crateApiToggleFtdiReset(enable: enable);

Future<void> resetCpuApi() => NativeConfig.instance.api.crateApiResetCpuApi();

Future<void> shutdownBoardApi() =>
    NativeConfig.instance.api.crateApiShutdownBoardApi();

Future<void> writeGpioRegisterApi({
  required int addr,
  required U8Array4 dataPayload,
}) => NativeConfig.instance.api.crateApiWriteGpioRegisterApi(
  addr: addr,
  dataPayload: dataPayload,
);

Future<U8Array4> readGpioRegisterApi({required int addr}) =>
    NativeConfig.instance.api.crateApiReadGpioRegisterApi(addr: addr);

/// Retrieves current board telemetry (frequency, voltage, temperature, etc.)
Future<TelemetryData> getTelemetry() =>
    NativeConfig.instance.api.crateApiGetTelemetry();

class InterfaceMuxStatus {
  final bool bromSdEn;
  final bool bromSdSel;
  final int uartAsicFtdiMux;
  final int jtagAsicFtdiMux;
  final bool sataERedriverEn;
  final bool displayportRedriver;
  final int pmodSpi;
  final int i2SAudioDacGain;

  const InterfaceMuxStatus({
    required this.bromSdEn,
    required this.bromSdSel,
    required this.uartAsicFtdiMux,
    required this.jtagAsicFtdiMux,
    required this.sataERedriverEn,
    required this.displayportRedriver,
    required this.pmodSpi,
    required this.i2SAudioDacGain,
  });

  @override
  int get hashCode =>
      bromSdEn.hashCode ^
      bromSdSel.hashCode ^
      uartAsicFtdiMux.hashCode ^
      jtagAsicFtdiMux.hashCode ^
      sataERedriverEn.hashCode ^
      displayportRedriver.hashCode ^
      pmodSpi.hashCode ^
      i2SAudioDacGain.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InterfaceMuxStatus &&
          runtimeType == other.runtimeType &&
          bromSdEn == other.bromSdEn &&
          bromSdSel == other.bromSdSel &&
          uartAsicFtdiMux == other.uartAsicFtdiMux &&
          jtagAsicFtdiMux == other.jtagAsicFtdiMux &&
          sataERedriverEn == other.sataERedriverEn &&
          displayportRedriver == other.displayportRedriver &&
          pmodSpi == other.pmodSpi &&
          i2SAudioDacGain == other.i2SAudioDacGain;
}

class IntrAlertStatus {
  final bool asicsEthInt;
  final bool alertSigAsicsMonitor;
  final bool adcInt;
  final bool motherboardEthInt;

  const IntrAlertStatus({
    required this.asicsEthInt,
    required this.alertSigAsicsMonitor,
    required this.adcInt,
    required this.motherboardEthInt,
  });

  @override
  int get hashCode =>
      asicsEthInt.hashCode ^
      alertSigAsicsMonitor.hashCode ^
      adcInt.hashCode ^
      motherboardEthInt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IntrAlertStatus &&
          runtimeType == other.runtimeType &&
          asicsEthInt == other.asicsEthInt &&
          alertSigAsicsMonitor == other.alertSigAsicsMonitor &&
          adcInt == other.adcInt &&
          motherboardEthInt == other.motherboardEthInt;
}

class PcieStatus {
  final bool pcieStatus;
  final int pcieOutputs;
  final bool pcieSsSelTri;
  final int pcieBufferState;

  const PcieStatus({
    required this.pcieStatus,
    required this.pcieOutputs,
    required this.pcieSsSelTri,
    required this.pcieBufferState,
  });

  static Future<PcieStatus> default_() =>
      NativeConfig.instance.api.crateApiPcieStatusDefault();

  @override
  int get hashCode =>
      pcieStatus.hashCode ^
      pcieOutputs.hashCode ^
      pcieSsSelTri.hashCode ^
      pcieBufferState.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PcieStatus &&
          runtimeType == other.runtimeType &&
          pcieStatus == other.pcieStatus &&
          pcieOutputs == other.pcieOutputs &&
          pcieSsSelTri == other.pcieSsSelTri &&
          pcieBufferState == other.pcieBufferState;
}

class PwrClkStatus {
  final bool pmicControl;
  final int sataConnectorPower;
  final bool serdesClkEn;
  final bool i2CMuxReset;
  final bool ftdiReset;

  const PwrClkStatus({
    required this.pmicControl,
    required this.sataConnectorPower,
    required this.serdesClkEn,
    required this.i2CMuxReset,
    required this.ftdiReset,
  });

  @override
  int get hashCode =>
      pmicControl.hashCode ^
      sataConnectorPower.hashCode ^
      serdesClkEn.hashCode ^
      i2CMuxReset.hashCode ^
      ftdiReset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PwrClkStatus &&
          runtimeType == other.runtimeType &&
          pmicControl == other.pmicControl &&
          sataConnectorPower == other.sataConnectorPower &&
          serdesClkEn == other.serdesClkEn &&
          i2CMuxReset == other.i2CMuxReset &&
          ftdiReset == other.ftdiReset;
}

class TelemetryData {
  final String name;
  final bool powerOn;
  final double frequency;
  final double voltage;
  final double temperature;
  final double humidity;
  final double power;
  final double pressure;

  const TelemetryData({
    required this.name,
    required this.powerOn,
    required this.frequency,
    required this.voltage,
    required this.temperature,
    required this.humidity,
    required this.power,
    required this.pressure,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      powerOn.hashCode ^
      frequency.hashCode ^
      voltage.hashCode ^
      temperature.hashCode ^
      humidity.hashCode ^
      power.hashCode ^
      pressure.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TelemetryData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          powerOn == other.powerOn &&
          frequency == other.frequency &&
          voltage == other.voltage &&
          temperature == other.temperature &&
          humidity == other.humidity &&
          power == other.power &&
          pressure == other.pressure;
}

class U8Array4 extends NonGrowableListView<int> {
  static const arraySize = 4;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array4(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array4.init() : this(Uint8List(arraySize));
}

class UsbStatus {
  final bool usb0PowSw;
  final bool usb0Reset;
  final bool usb0HsLed;
  final bool usb0DetectLed;
  final bool usb1PowSw;
  final bool usb1Reset;
  final bool usb1HsLed;
  final bool usb1DetectLed;
  final bool usbcEsdStatus;

  const UsbStatus({
    required this.usb0PowSw,
    required this.usb0Reset,
    required this.usb0HsLed,
    required this.usb0DetectLed,
    required this.usb1PowSw,
    required this.usb1Reset,
    required this.usb1HsLed,
    required this.usb1DetectLed,
    required this.usbcEsdStatus,
  });

  static Future<UsbStatus> default_() =>
      NativeConfig.instance.api.crateApiUsbStatusDefault();

  @override
  int get hashCode =>
      usb0PowSw.hashCode ^
      usb0Reset.hashCode ^
      usb0HsLed.hashCode ^
      usb0DetectLed.hashCode ^
      usb1PowSw.hashCode ^
      usb1Reset.hashCode ^
      usb1HsLed.hashCode ^
      usb1DetectLed.hashCode ^
      usbcEsdStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UsbStatus &&
          runtimeType == other.runtimeType &&
          usb0PowSw == other.usb0PowSw &&
          usb0Reset == other.usb0Reset &&
          usb0HsLed == other.usb0HsLed &&
          usb0DetectLed == other.usb0DetectLed &&
          usb1PowSw == other.usb1PowSw &&
          usb1Reset == other.usb1Reset &&
          usb1HsLed == other.usb1HsLed &&
          usb1DetectLed == other.usb1DetectLed &&
          usbcEsdStatus == other.usbcEsdStatus;
}
