// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class NativeConfig
    extends
        BaseEntrypoint<NativeConfigApi, NativeConfigApiImpl, NativeConfigWire> {
  @internal
  static final instance = NativeConfig._();

  NativeConfig._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    NativeConfigApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required NativeConfigApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<NativeConfigApiImpl, NativeConfigWire>
  get apiImplConstructor => NativeConfigApiImpl.new;

  @override
  WireConstructor<NativeConfigWire> get wireConstructor =>
      NativeConfigWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1704231541;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'native',
        ioDirectory: 'native/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class NativeConfigApi extends BaseApi {
  Future<void> crateApiConnectToBoard({required String targetMac});

  Future<TelemetryData> crateApiGetTelemetry();

  Future<PcieStatus> crateApiPcieStatusDefault();

  Future<U8Array4> crateApiReadGpioRegisterApi({required int addr});

  Future<InterfaceMuxStatus> crateApiReadInterfaceMuxStatus();

  Future<IntrAlertStatus> crateApiReadIntrAlertStatus();

  Future<PcieStatus> crateApiReadPcieStatus();

  Future<PwrClkStatus> crateApiReadPwrClkStatus();

  Future<UsbStatus> crateApiReadUsbStatus();

  Future<void> crateApiResetCpuApi();

  Future<void> crateApiSetPcieOutputs({required int level});

  Future<void> crateApiSetSataPower({required int level});

  Future<void> crateApiSetSimulationMode({required bool on_});

  Future<void> crateApiShutdownBoardApi();

  Future<void> crateApiToggleFtdiReset({required bool enable});

  Future<void> crateApiToggleI2CMuxReset({required bool enable});

  Future<bool> crateApiTogglePower();

  Future<void> crateApiToggleSerdesClock({required bool enable});

  Future<void> crateApiToggleUsb0Power({required bool enable});

  Future<void> crateApiToggleUsb0Reset({required bool enable});

  Future<void> crateApiToggleUsb1Power({required bool enable});

  Future<void> crateApiToggleUsb1Reset({required bool enable});

  Future<UsbStatus> crateApiUsbStatusDefault();

  Future<void> crateApiWriteGpioRegisterApi({
    required int addr,
    required U8Array4 dataPayload,
  });
}

class NativeConfigApiImpl extends NativeConfigApiImplPlatform
    implements NativeConfigApi {
  NativeConfigApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiConnectToBoard({required String targetMac}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(targetMac, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiConnectToBoardConstMeta,
        argValues: [targetMac],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiConnectToBoardConstMeta => const TaskConstMeta(
    debugName: "connect_to_board",
    argNames: ["targetMac"],
  );

  @override
  Future<TelemetryData> crateApiGetTelemetry() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_telemetry_data,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetTelemetryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetTelemetryConstMeta =>
      const TaskConstMeta(debugName: "get_telemetry", argNames: []);

  @override
  Future<PcieStatus> crateApiPcieStatusDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pcie_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPcieStatusDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPcieStatusDefaultConstMeta =>
      const TaskConstMeta(debugName: "pcie_status_default", argNames: []);

  @override
  Future<U8Array4> crateApiReadGpioRegisterApi({required int addr}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(addr, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_8_array_4,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadGpioRegisterApiConstMeta,
        argValues: [addr],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadGpioRegisterApiConstMeta =>
      const TaskConstMeta(
        debugName: "read_gpio_register_api",
        argNames: ["addr"],
      );

  @override
  Future<InterfaceMuxStatus> crateApiReadInterfaceMuxStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_interface_mux_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadInterfaceMuxStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadInterfaceMuxStatusConstMeta =>
      const TaskConstMeta(debugName: "read_interface_mux_status", argNames: []);

  @override
  Future<IntrAlertStatus> crateApiReadIntrAlertStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_intr_alert_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadIntrAlertStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadIntrAlertStatusConstMeta =>
      const TaskConstMeta(debugName: "read_intr_alert_status", argNames: []);

  @override
  Future<PcieStatus> crateApiReadPcieStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pcie_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadPcieStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadPcieStatusConstMeta =>
      const TaskConstMeta(debugName: "read_pcie_status", argNames: []);

  @override
  Future<PwrClkStatus> crateApiReadPwrClkStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pwr_clk_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadPwrClkStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadPwrClkStatusConstMeta =>
      const TaskConstMeta(debugName: "read_pwr_clk_status", argNames: []);

  @override
  Future<UsbStatus> crateApiReadUsbStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usb_status,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiReadUsbStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReadUsbStatusConstMeta =>
      const TaskConstMeta(debugName: "read_usb_status", argNames: []);

  @override
  Future<void> crateApiResetCpuApi() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiResetCpuApiConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResetCpuApiConstMeta =>
      const TaskConstMeta(debugName: "reset_cpu_api", argNames: []);

  @override
  Future<void> crateApiSetPcieOutputs({required int level}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(level, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetPcieOutputsConstMeta,
        argValues: [level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetPcieOutputsConstMeta =>
      const TaskConstMeta(debugName: "set_pcie_outputs", argNames: ["level"]);

  @override
  Future<void> crateApiSetSataPower({required int level}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(level, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetSataPowerConstMeta,
        argValues: [level],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetSataPowerConstMeta =>
      const TaskConstMeta(debugName: "set_sata_power", argNames: ["level"]);

  @override
  Future<void> crateApiSetSimulationMode({required bool on_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetSimulationModeConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetSimulationModeConstMeta =>
      const TaskConstMeta(debugName: "set_simulation_mode", argNames: ["on_"]);

  @override
  Future<void> crateApiShutdownBoardApi() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiShutdownBoardApiConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiShutdownBoardApiConstMeta =>
      const TaskConstMeta(debugName: "shutdown_board_api", argNames: []);

  @override
  Future<void> crateApiToggleFtdiReset({required bool enable}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiToggleFtdiResetConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiToggleFtdiResetConstMeta =>
      const TaskConstMeta(debugName: "toggle_ftdi_reset", argNames: ["enable"]);

  @override
  Future<void> crateApiToggleI2CMuxReset({required bool enable}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiToggleI2CMuxResetConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiToggleI2CMuxResetConstMeta => const TaskConstMeta(
    debugName: "toggle_i2c_mux_reset",
    argNames: ["enable"],
  );

  @override
  Future<bool> crateApiTogglePower() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiTogglePowerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTogglePowerConstMeta =>
      const TaskConstMeta(debugName: "toggle_power", argNames: []);

  @override
  Future<void> crateApiToggleSerdesClock({required bool enable}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiToggleSerdesClockConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiToggleSerdesClockConstMeta => const TaskConstMeta(
    debugName: "toggle_serdes_clock",
    argNames: ["enable"],
  );

  @override
  Future<void> crateApiToggleUsb0Power({required bool enable}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiToggleUsb0PowerConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiToggleUsb0PowerConstMeta =>
      const TaskConstMeta(debugName: "toggle_usb0_power", argNames: ["enable"]);

  @override
  Future<void> crateApiToggleUsb0Reset({required bool enable}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiToggleUsb0ResetConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiToggleUsb0ResetConstMeta =>
      const TaskConstMeta(debugName: "toggle_usb0_reset", argNames: ["enable"]);

  @override
  Future<void> crateApiToggleUsb1Power({required bool enable}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiToggleUsb1PowerConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiToggleUsb1PowerConstMeta =>
      const TaskConstMeta(debugName: "toggle_usb1_power", argNames: ["enable"]);

  @override
  Future<void> crateApiToggleUsb1Reset({required bool enable}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(enable, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiToggleUsb1ResetConstMeta,
        argValues: [enable],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiToggleUsb1ResetConstMeta =>
      const TaskConstMeta(debugName: "toggle_usb1_reset", argNames: ["enable"]);

  @override
  Future<UsbStatus> crateApiUsbStatusDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usb_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiUsbStatusDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiUsbStatusDefaultConstMeta =>
      const TaskConstMeta(debugName: "usb_status_default", argNames: []);

  @override
  Future<void> crateApiWriteGpioRegisterApi({
    required int addr,
    required U8Array4 dataPayload,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(addr, serializer);
          sse_encode_u_8_array_4(dataPayload, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWriteGpioRegisterApiConstMeta,
        argValues: [addr, dataPayload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWriteGpioRegisterApiConstMeta =>
      const TaskConstMeta(
        debugName: "write_gpio_register_api",
        argNames: ["addr", "dataPayload"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  InterfaceMuxStatus dco_decode_interface_mux_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return InterfaceMuxStatus(
      bromSdEn: dco_decode_bool(arr[0]),
      bromSdSel: dco_decode_bool(arr[1]),
      uartAsicFtdiMux: dco_decode_u_32(arr[2]),
      jtagAsicFtdiMux: dco_decode_u_32(arr[3]),
      sataERedriverEn: dco_decode_bool(arr[4]),
      displayportRedriver: dco_decode_bool(arr[5]),
      pmodSpi: dco_decode_u_32(arr[6]),
      i2SAudioDacGain: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  IntrAlertStatus dco_decode_intr_alert_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return IntrAlertStatus(
      asicsEthInt: dco_decode_bool(arr[0]),
      alertSigAsicsMonitor: dco_decode_bool(arr[1]),
      adcInt: dco_decode_bool(arr[2]),
      motherboardEthInt: dco_decode_bool(arr[3]),
    );
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PcieStatus dco_decode_pcie_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return PcieStatus(
      pcieStatus: dco_decode_bool(arr[0]),
      pcieOutputs: dco_decode_u_32(arr[1]),
      pcieSsSelTri: dco_decode_bool(arr[2]),
      pcieBufferState: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  PwrClkStatus dco_decode_pwr_clk_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PwrClkStatus(
      pmicControl: dco_decode_bool(arr[0]),
      sataConnectorPower: dco_decode_u_32(arr[1]),
      serdesClkEn: dco_decode_bool(arr[2]),
      i2CMuxReset: dco_decode_bool(arr[3]),
      ftdiReset: dco_decode_bool(arr[4]),
    );
  }

  @protected
  TelemetryData dco_decode_telemetry_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return TelemetryData(
      name: dco_decode_String(arr[0]),
      powerOn: dco_decode_bool(arr[1]),
      frequency: dco_decode_f_32(arr[2]),
      voltage: dco_decode_f_32(arr[3]),
      temperature: dco_decode_f_32(arr[4]),
      humidity: dco_decode_f_32(arr[5]),
      power: dco_decode_f_32(arr[6]),
      pressure: dco_decode_f_32(arr[7]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  U8Array4 dco_decode_u_8_array_4(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return U8Array4(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UsbStatus dco_decode_usb_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return UsbStatus(
      usb0PowSw: dco_decode_bool(arr[0]),
      usb0Reset: dco_decode_bool(arr[1]),
      usb0HsLed: dco_decode_bool(arr[2]),
      usb0DetectLed: dco_decode_bool(arr[3]),
      usb1PowSw: dco_decode_bool(arr[4]),
      usb1Reset: dco_decode_bool(arr[5]),
      usb1HsLed: dco_decode_bool(arr[6]),
      usb1DetectLed: dco_decode_bool(arr[7]),
      usbcEsdStatus: dco_decode_bool(arr[8]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  InterfaceMuxStatus sse_decode_interface_mux_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bromSdEn = sse_decode_bool(deserializer);
    var var_bromSdSel = sse_decode_bool(deserializer);
    var var_uartAsicFtdiMux = sse_decode_u_32(deserializer);
    var var_jtagAsicFtdiMux = sse_decode_u_32(deserializer);
    var var_sataERedriverEn = sse_decode_bool(deserializer);
    var var_displayportRedriver = sse_decode_bool(deserializer);
    var var_pmodSpi = sse_decode_u_32(deserializer);
    var var_i2SAudioDacGain = sse_decode_u_32(deserializer);
    return InterfaceMuxStatus(
      bromSdEn: var_bromSdEn,
      bromSdSel: var_bromSdSel,
      uartAsicFtdiMux: var_uartAsicFtdiMux,
      jtagAsicFtdiMux: var_jtagAsicFtdiMux,
      sataERedriverEn: var_sataERedriverEn,
      displayportRedriver: var_displayportRedriver,
      pmodSpi: var_pmodSpi,
      i2SAudioDacGain: var_i2SAudioDacGain,
    );
  }

  @protected
  IntrAlertStatus sse_decode_intr_alert_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_asicsEthInt = sse_decode_bool(deserializer);
    var var_alertSigAsicsMonitor = sse_decode_bool(deserializer);
    var var_adcInt = sse_decode_bool(deserializer);
    var var_motherboardEthInt = sse_decode_bool(deserializer);
    return IntrAlertStatus(
      asicsEthInt: var_asicsEthInt,
      alertSigAsicsMonitor: var_alertSigAsicsMonitor,
      adcInt: var_adcInt,
      motherboardEthInt: var_motherboardEthInt,
    );
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PcieStatus sse_decode_pcie_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pcieStatus = sse_decode_bool(deserializer);
    var var_pcieOutputs = sse_decode_u_32(deserializer);
    var var_pcieSsSelTri = sse_decode_bool(deserializer);
    var var_pcieBufferState = sse_decode_u_32(deserializer);
    return PcieStatus(
      pcieStatus: var_pcieStatus,
      pcieOutputs: var_pcieOutputs,
      pcieSsSelTri: var_pcieSsSelTri,
      pcieBufferState: var_pcieBufferState,
    );
  }

  @protected
  PwrClkStatus sse_decode_pwr_clk_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pmicControl = sse_decode_bool(deserializer);
    var var_sataConnectorPower = sse_decode_u_32(deserializer);
    var var_serdesClkEn = sse_decode_bool(deserializer);
    var var_i2CMuxReset = sse_decode_bool(deserializer);
    var var_ftdiReset = sse_decode_bool(deserializer);
    return PwrClkStatus(
      pmicControl: var_pmicControl,
      sataConnectorPower: var_sataConnectorPower,
      serdesClkEn: var_serdesClkEn,
      i2CMuxReset: var_i2CMuxReset,
      ftdiReset: var_ftdiReset,
    );
  }

  @protected
  TelemetryData sse_decode_telemetry_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_powerOn = sse_decode_bool(deserializer);
    var var_frequency = sse_decode_f_32(deserializer);
    var var_voltage = sse_decode_f_32(deserializer);
    var var_temperature = sse_decode_f_32(deserializer);
    var var_humidity = sse_decode_f_32(deserializer);
    var var_power = sse_decode_f_32(deserializer);
    var var_pressure = sse_decode_f_32(deserializer);
    return TelemetryData(
      name: var_name,
      powerOn: var_powerOn,
      frequency: var_frequency,
      voltage: var_voltage,
      temperature: var_temperature,
      humidity: var_humidity,
      power: var_power,
      pressure: var_pressure,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  U8Array4 sse_decode_u_8_array_4(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return U8Array4(inner);
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UsbStatus sse_decode_usb_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_usb0PowSw = sse_decode_bool(deserializer);
    var var_usb0Reset = sse_decode_bool(deserializer);
    var var_usb0HsLed = sse_decode_bool(deserializer);
    var var_usb0DetectLed = sse_decode_bool(deserializer);
    var var_usb1PowSw = sse_decode_bool(deserializer);
    var var_usb1Reset = sse_decode_bool(deserializer);
    var var_usb1HsLed = sse_decode_bool(deserializer);
    var var_usb1DetectLed = sse_decode_bool(deserializer);
    var var_usbcEsdStatus = sse_decode_bool(deserializer);
    return UsbStatus(
      usb0PowSw: var_usb0PowSw,
      usb0Reset: var_usb0Reset,
      usb0HsLed: var_usb0HsLed,
      usb0DetectLed: var_usb0DetectLed,
      usb1PowSw: var_usb1PowSw,
      usb1Reset: var_usb1Reset,
      usb1HsLed: var_usb1HsLed,
      usb1DetectLed: var_usb1DetectLed,
      usbcEsdStatus: var_usbcEsdStatus,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_interface_mux_status(
    InterfaceMuxStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.bromSdEn, serializer);
    sse_encode_bool(self.bromSdSel, serializer);
    sse_encode_u_32(self.uartAsicFtdiMux, serializer);
    sse_encode_u_32(self.jtagAsicFtdiMux, serializer);
    sse_encode_bool(self.sataERedriverEn, serializer);
    sse_encode_bool(self.displayportRedriver, serializer);
    sse_encode_u_32(self.pmodSpi, serializer);
    sse_encode_u_32(self.i2SAudioDacGain, serializer);
  }

  @protected
  void sse_encode_intr_alert_status(
    IntrAlertStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.asicsEthInt, serializer);
    sse_encode_bool(self.alertSigAsicsMonitor, serializer);
    sse_encode_bool(self.adcInt, serializer);
    sse_encode_bool(self.motherboardEthInt, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_pcie_status(PcieStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.pcieStatus, serializer);
    sse_encode_u_32(self.pcieOutputs, serializer);
    sse_encode_bool(self.pcieSsSelTri, serializer);
    sse_encode_u_32(self.pcieBufferState, serializer);
  }

  @protected
  void sse_encode_pwr_clk_status(PwrClkStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.pmicControl, serializer);
    sse_encode_u_32(self.sataConnectorPower, serializer);
    sse_encode_bool(self.serdesClkEn, serializer);
    sse_encode_bool(self.i2CMuxReset, serializer);
    sse_encode_bool(self.ftdiReset, serializer);
  }

  @protected
  void sse_encode_telemetry_data(TelemetryData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.powerOn, serializer);
    sse_encode_f_32(self.frequency, serializer);
    sse_encode_f_32(self.voltage, serializer);
    sse_encode_f_32(self.temperature, serializer);
    sse_encode_f_32(self.humidity, serializer);
    sse_encode_f_32(self.power, serializer);
    sse_encode_f_32(self.pressure, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_u_8_array_4(U8Array4 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.inner, serializer);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usb_status(UsbStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.usb0PowSw, serializer);
    sse_encode_bool(self.usb0Reset, serializer);
    sse_encode_bool(self.usb0HsLed, serializer);
    sse_encode_bool(self.usb0DetectLed, serializer);
    sse_encode_bool(self.usb1PowSw, serializer);
    sse_encode_bool(self.usb1Reset, serializer);
    sse_encode_bool(self.usb1HsLed, serializer);
    sse_encode_bool(self.usb1DetectLed, serializer);
    sse_encode_bool(self.usbcEsdStatus, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
